version: '2'

services:
  mariadb:
    image: 'bitnami/mariadb:latest'
    volumes:
      - 'persist-db:/bitnami/mariadb'
  drupal:
    image: 'bitnami/drupal:latest'
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - 'persist-drupal:/bitnami/drupal'
      - 'persist-apache:/bitnami/apache'
      - 'php_data:/bitnami/php'
    depends_on:
      - mariadb
volumes:
  mariadb_data:
    driver: local
  drupal_data:
    driver: local
  apache_data:
    driver: local
  php_data:
    driver: local
